apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-site-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-site
  template:
    metadata:
      labels:
        app: resume-site
    spec:
      containers:
        - name: personal-site
          image: 471112593558.dkr.ecr.us-east-1.amazonaws.com/personal-site:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume-site-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: resume-site
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-site-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: resume-site-service
              port:
                number: 80