name: Build/Destroy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  Build_Or_Destroy_Infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@main
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Download kubectl
      run: curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.3/2024-04-19/bin/linux/amd64/kubectl

    - name: Make kubectl executable
      run: chmod +x ./kubectl

    - name: Create bin directory
      run: mkdir -p $HOME/bin

    - name: Move kubectl to bin
      run: cp ./kubectl $HOME/bin/kubectl

    - name: Add kubectl to PATH
      run: echo 'export PATH=$HOME/bin:$PATH' >> $GITHUB_ENV

    - name: Initialize Terraform 
      run : terraform init
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Validate Terraform configuration
      run: terraform validate

    - name: Remove K8 resources if destroying Infra
      if: ${{endsWith(github.event.head_commit.message, '[destroy]')}}
      run: |
          EKS_CLUSTER_NAME=$(aws eks list-clusters --region ${{ secrets.AWS_REGION }} --output text | awk '{print $2}')
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name $EKS_CLUSTER_NAME
          kubectl delete -f websitedeployment.yml

    - name: Destroy Terraform Infra after taking down K8 resources
      if: ${{endsWith(github.event.head_commit.message, '[destroy]')}}
      run: terraform destroy -auto-approve


    - name: Terraform Apply
      if: ${{ !endsWith(github.event.head_commit.message, '[destroy]')}}
      run: terraform apply -auto-approve